name: aws_s3_client
description: Client library to interact with the AWS S3 API (and other compatible S3 services, as Yandex Cloud Storage)
version: 0.3.1
homepage: https://github.com/idrats/aws_s3_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http_client: ^1.5.1
  xml: ^5.1.2
  http: ^0.13.3
  path: ^1.8.0
  mime: ^1.0.0

dev_dependencies:
  test: ^1.17.10
